[2021-08-05 20:00:04,203] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: tutorial.testairflow 2021-08-05T00:00:00+00:00 [queued]>
[2021-08-05 20:00:04,207] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: tutorial.testairflow 2021-08-05T00:00:00+00:00 [queued]>
[2021-08-05 20:00:04,207] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-05 20:00:04,207] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2021-08-05 20:00:04,207] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-05 20:00:04,211] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): testairflow> on 2021-08-05T00:00:00+00:00
[2021-08-05 20:00:04,213] {standard_task_runner.py:52} INFO - Started process 22703 to run task
[2021-08-05 20:00:04,218] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial', 'testairflow', '2021-08-05T00:00:00+00:00', '--job-id', '20', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Airflow.py', '--cfg-path', '/var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T/tmp6_m01_jl', '--error-file', '/var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T/tmprd6ka8ao']
[2021-08-05 20:00:04,220] {standard_task_runner.py:77} INFO - Job 20: Subtask testairflow
[2021-08-05 20:00:04,244] {logging_mixin.py:104} INFO - Running <TaskInstance: tutorial.testairflow 2021-08-05T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-08-05 20:00:04,267] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=testairflow
AIRFLOW_CTX_EXECUTION_DATE=2021-08-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-05T00:00:00+00:00
[2021-08-05 20:00:04,268] {subprocess.py:52} INFO - Tmp dir root location: 
 /var/folders/kh/c93m3t_d2rgcvcbylylqtx240000gn/T
[2021-08-05 20:00:04,269] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'python /Users/kennethlau/Desktop/a_pipeline.py']
[2021-08-05 20:00:04,274] {subprocess.py:74} INFO - Output:
[2021-08-05 20:00:04,349] {subprocess.py:78} INFO - Traceback (most recent call last):
[2021-08-05 20:00:04,350] {subprocess.py:78} INFO -   File "/Users/kennethlau/Desktop/a_pipeline.py", line 1, in <module>
[2021-08-05 20:00:04,350] {subprocess.py:78} INFO -     from matplotlib import pyplot
[2021-08-05 20:00:04,350] {subprocess.py:78} INFO - ModuleNotFoundError: No module named 'matplotlib'
[2021-08-05 20:00:04,352] {subprocess.py:82} INFO - Command exited with return code 1
[2021-08-05 20:00:04,358] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/kennethlau/airflow/airflow-tutorial/env_airflow/lib/python3.8/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-08-05 20:00:04,364] {taskinstance.py:1544} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial, task_id=testairflow, execution_date=20210805T000000, start_date=20210806T000004, end_date=20210806T000004
[2021-08-05 20:00:04,423] {local_task_job.py:149} INFO - Task exited with return code 1
